services:
  frontend:
    build: frontend
    ports:
      - "3010:3000"
    environment:
      BACKEND_URL: "http://backend:8000"

  backend:
    build: backend
    environment:
      APP_ENV: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:8.6.3-alpine
    restart: always
