services:
  frontend:
    build: frontend
    ports:
      - "3010:3000"
    env_file: ./frontend/.env

  backend:
    build: backend
    env_file: ./backend/.env

  postgres:
    image: postgres:18.4-alpine
    env_file: ./.env.postgres
