services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    environment:
      PUBLIC_ENV__API_URL: https://mrdsx-observer-39f3b422.fastapicloud.dev

  firebase:
    build: firebase
    ports:
      - "4000:4000"
      - "8080:8080"

  redis:
    image: redis:8.6.2-alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: always
