MAX_RESPONSE_TIME_SECONDS = 5

REPORTS_RETENTION_WINDOW_DAYS = 30
LOGGING_INTERVAL_MINUTES = 5
CACHE_TTL_SECONDS = 60 * (LOGGING_INTERVAL_MINUTES * 2)


class FirestoreKeys:
    PROJECTS_REPORTS = "projects_reports"


class RedisKeys:
    PROJECTS_REPORTS = "projects_reports"
